### ISSUE TITLE
pythorch cuda problem.    

### ISSUE THREAD

**Issue by flydragon2018** [e4s2022/e4s#25]
/python3.8/site-packages/torch/cuda/__init__.py", line 190, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (101) : invalid device ordinal at /pytorch/aten/src/THC/THCGeneral.cpp:47

**Comment by flydragon2018** [comment]
something wrong with gpu.

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

~/e4s$ nvidia-smi
No devices were found
(e4s) zzl@zzl-N960Kx:~/e4s$ lspci -k | grep -A 2 -E "(VGA|3D)"
00:02.0 VGA compatible controller: Intel Corporation Device 9bc5 (rev 05)
	Subsystem: CLEVO/KAPOK Computer Device 2112
	Kernel driver in use: i915
--
01:00.0 VGA compatible controller: NVIDIA Corporation Device 249d (rev ff)
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia

**Comment by flydragon2018** [comment]
solved by install compatible version.
